CBIIT/mtp-frontend

package.json, yarn.lock
upgrade protvista package to 2.7.4
=> upgrade protvista package to 2.7.4

src/sections/evidence/SomaticMutation/SnvByGeneTab.js
In this PR, The following change has happen for SNV By Gene table:
- Sorting and Downloading functionality are implemented.
=> PPDC-111 (SNV By Gene)

src/sections/evidence/SomaticMutation/SnvByVariantTab.js
In this PR, The following change has happen:
- Sorting and Downloading functionality are implemented.
=> PPDC-112 (SNV By Variant Table)

src/sections/evidence/SomaticMutation/CnvByGeneTab.js
In this PR, The following change has happen for CNV By Gene table:
- Sorting and Downloading functionality are implemented.
=> PPDC-110 (CNV By Gene)

src/App.js, src/components/RMTL/RMTLPopover.js, src/constants.js, src/pages/RMTLDocPage/index.js, src/pages/RMTLPage/RMTLPage.js
Update the URL from RMLT to PMTL
=> Update the URL from RMTL to PMTL

src/sections/evidence/SomaticMutation/SnvByVariantTab.js
In this PR, SNV by variant Table has been integrated with CHoP's column's configuration settings.
=> PPDC-157 (SNV By Variant)

src/sections/evidence/SomaticMutation/SnvByGeneTab.js
In this PR, SNV by gene Table has been integrated with CHoP's column's configuration settings.
=> PPDC-156 (SNV By Gene)

src/components/OtTableRF.js, src/components/RMTLTable.js, src/components/Table/Table.js
=> fix Pagination issue

src/pages/AboutPage/AboutView.js
Update the style of about page. 
1) make space before "Change Log" title same height as the other sections
2) remove white space after Change Log section.
=> update about page's design

src/pages/PedCancerDataNavPage/CHOPPage.js
Small Edit to remove warning for un used variables.
=> Remove unused variable

src/components/Search/PedSearch.js, src/pages/DiseasePage/ClassicAssociations.js, src/pages/PedCancerDataNavPage/CHOPPage.js, src/pages/PedCancerDataNavPage/PedCancerDataNav.gql, src/pages/TargetPage/ClassicAssociations.js
In this PR, URL to "Pediatric Cancer Data Navigation" page is added under Disease and Target Associated Page.
=> PPDC-395 (Add navigation page's link into Menu bar)

src/components/Search/PedSearch.js, src/pages/PedCancerDataNavPage/CHOPPage.js, src/pages/PedCancerDataNavPage/PedCancerDataNav.gql
In this PR, Pediatric Cancer Data Navigation Page has been integrated with GraphQl API. Now, user can see result based on the gene symbol and disease search. 
Related Ticket: PPDC-425
=> PPDC-425 (API Integration for Pediatric Cancer Data Navigation Page)

public/config.js, src/components/NCIFooter/Footer.js, src/config.js, src/constants.js, src/pages/AboutPage/AboutView.js, src/pages/HomePage/Version.js
In this PR, updated the version number which reads from os environment and updated the wording on about page. 
Related Ticket: PPDC-427 and  PPDC-424
=> update the wording on about page and versioning

src/components/NCIFooter/Footer.js, src/constants.js, src/pages/AboutPage/AboutView.js, src/pages/HomePage/Version.js
In this PR, versioning URL has been updated for Home page and Footer to point to the Change Log under About page.
Related Ticket: PPDC-423
=> PPDC-423 (Update Versioning URL to point to About Page)

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR, the description text for the Nav Page has been updated to display the correct number of targets with commas
=> PPDC-422-fix(display the correct number of targets and apply comma)

src/pages/AboutPage/AboutView.js, src/pages/HomePage/HomePage.js, src/pages/PMTLPage/PMTLPage.js, src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR, auto scroll to the top of the page has been added when visiting the following pages:
- Home Page  
- FDA PMTL Page
- About Page  
- Pediatric Cancer Data Navigation Page  
Related Ticket: PPDC-458
=> PPDC-458 (Add Scroll To Top for 4 pages)

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
This is small fix for correcting the result header color.
=> Fix coloring for PCDN page

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
This is small responsiveness fix under Pediatric Cancer Data Navigation Page for search container when displayed on smaller screen.
=> Fix search container responsiveness for smaller screen

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR, the page design for the Pediatric Cancer Data Navigation has been update with the following:
- Update PCDN title text color to "#368acb"
- Update "Gene Symbol" and "Disease" text color under search container to "#368acb"
- Update Search button, on hover or disabled to background color of "#3488c8" and text color of "white"
- Make text under title, "Search for a Target..." to be hex value of "#5c5f5e" and decrease letter spacing AND word spacing
- Update Result text color to "#368acb" Ex. "Found 36 Diseases with..." 
The rest stay as is.
Related Ticket: PPDC-422
=> PPDC-422 (Design Update 2)

src/components/NCIFooter/Footer.js, src/components/NCIFooter/index.js
1. Add HHS Vulnerability Disclosure link to the footer. 
2. Remove extra space.
=> Update the footer's style

src/components/Legend.js
PR changes score link's behavior on Target and disease page.  Click link will open a new tab . 
Refers PPDC-483
=> update the score link's behavior

src/components/NCIFooter/Footer.js
Refers PPDC 476
Changes:
NCI branding: bump up to next level of bold weight and decrease letterspacing on both lines
Add a slight bold on the headers "Contact Information" "More Information" "NIH Policies"
Lower case "s" in "Contact Us"
Move Version updates to left alignment with NCI branding
Center line "US Dept of Health and ..."
Remove extra line of space and bump up line "NIH...Turning Discovery into Health"
=> Footer Update

src/components/RMTLTable.js
Fix issue when pagination changes, the table does not scroll to the top.
=> fix table focus is not at the top

src/assets/PediatricDataCancer-MenuBar-Icon.svg, src/components/NCINavBar/NavBarView.js, src/components/NCINavBar/index.js, src/components/NavBar.js, src/components/NavPanel/SectionMenuItem.js, src/components/NavPanel/navPanelStyles.js, src/components/Page.js, src/components/Summary/SummaryItem.js, src/pages/AboutPage/AboutView.js, src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR:
- NCI Nav Bar has been updated to emphasize links to the new Pediatric Cancer Data Navigation(PCDN) page
- NCI Nav Bar height has been increase from 39px to 59px, as well as padding and fontSize for each items.
- About page has been renamed to "About Molecular Targets"
- All pages has been pushed down by 20px to provide space for new NCI Nav Bar height
Related Ticket: PPDC-480
=> PPDC-480(Under NCI Nav Bar, emphasize links to Pediatric Cancer Data Navigation(PCDN) page)

src/pages/HomePage/HomeBox.js
In this PR:
- The Home Page has been updated to include a link to the Pediatric Cancer Data Navigation(PCDN) page above the HomeBox.
Related Ticket: PPDC-481
=> PPDC-481(emphasize PCDN page under Home Page)

src/pages/NotFoundPage/MTPNotFoundPage.js, src/pages/NotFoundPage/index.js
In this PR:
- MTP Not found page has been implemented. 
- This new page will be replacing OT's Not Found Page and will be displayed whenever requested page is unavailable or doesn’t exist.
Related Ticket: PPDC-489
=> PPDC-489 (MTP Not Found Page)

src/components/BasePageMTP.js, src/pages/PMTLDocPage/index.js, src/pages/PMTLPage/PMTLPage.js
Remove OT search Bar from PMTL page
Refers - PPDC-510
=> update the PMTL page

src/components/NCIFooter/Footer.js
In this PR:
- Footer has been updated to be aligned in the center horizontally.
Related Ticket: PPDC-503
=> PPDC-503(Footer alignment to the center)

src/config.js, src/utils/externalAPI.js
updated CHoP R server's API  to include new parameter and use CHoP dev version of API. 
Once verified by both parties,  we will change the API version to Prod.
=> update CHoP's API

src/sections/common/OpenPedCanGeneExpression/Body.js
Additional changes needed to add extra columns to download file.
=> add extra columns to download file

src/sections/common/OpenPedCanGeneExpression/Body.js
=> update the plot's width

src/config.js
change the ChoP API to prod version
=> change the ChoP API to prod version

src/pages/AboutPage/AboutView.js
In this PR:
- About Page has been updated to include the following additional dataset description:
- Pediatric Cancer Disease
- The Genotype-Tissue Expression (GTEx)
- Pediatric Cancer Data Processing
=> PPDC-544 (Update About Page)

src/components/Table/DataDownloader.js, src/sections/common/OpenPedCanSomaticAlterations/Body.js, src/sections/common/OpenPedCanSomaticAlterations/CnvByGeneTab.js, src/sections/common/OpenPedCanSomaticAlterations/FusionByGeneTab.js, src/sections/common/OpenPedCanSomaticAlterations/FusionTab.js, src/sections/common/OpenPedCanSomaticAlterations/SnvByGeneTab.js, src/sections/common/OpenPedCanSomaticAlterations/SnvByVariantTab.js, src/sections/evidence/OpenPedCanSomaticAlterations/SomaticAlterationsQuery.gql, src/sections/target/OpenPedCanSomaticAlterations/SomaticAlterationsQuery.gql
In this PR:
- "API Query" button has been added to all "OpenPedCan Somatic Alterations" widget tables
- Update API drawer text and add external link icon
Related Ticket: PPDC-548
=> PPDC-548 (Add GraphQL playground to OpenPedCan Somatic Alterations)

src/App.js, src/GlobalQuery.js, src/components/NCIFooter/index.js, src/pages/AboutPage/AboutView.js
Merging ot-sync and mvp branches has cause for three branches to be excluded. This PR has brought back those 3 branches or 4 PR to mvp branch. To see the full commit details look into the previous PR:
- #154 
- #155 
- #156 
- #158
=> revert missing branches

public/index.html, src/App.js, src/client.js, src/components/NCINavBar/NavBarView.js, src/components/NCINavBar/components/DropdownItemsMenu.js, src/components/NCINavBar/components/DropdownMenu.js, src/components/NCINavBar/index.js, src/pages/AboutPage/AboutView.js, src/pages/ChangeLogPage/ChangeLogView.js, src/pages/ChangeLogPage/index.js
In this PR, 
I implemented the new design of about dropdown menu and restyle the menu bar as Hannah requested. 
We separate the change log from about page, it has its own page
=> Update the Change log page

src/components/NCINavBar/NavBarView.js, src/components/NCINavBar/components/DropdownItemsMenu.js, src/components/NCINavBar/components/DropdownMenu.js
Update the way to highlight the active menu item 
Related ticket PPDC-688
=> Update the way to highlight the active menu item

src/pages/PMTLPage/PMTLPage.js
update the search behavior
related ticket ppdc-89
=> update the search behavior

src/components/NCINavBar/SmallerScreenNB.js, src/pages/HomePage/HomeBox.js
In this PR:
- Small improvement for a previous PR: https://github.com/CBIIT/mtp-frontend/pull/189
- Improvement involves around aligning hamburger or closing menu icon with home search box
Related Ticket: PPDC-696, PPDC-695
=> PPDC-696 (NavBar improvement)

public/index.html, src/components/NCIFooter/Footer.js, src/components/NCIFooter/index.js
In this PR:
- Implement responsive and mobile friendly Footer
- Footer main title/Logo is clickable to NCI site
Related Ticket: PPDC-711
=> PPDC-711: (implement responsive Footer)

src/pages/HomePage/HomeBox.js, src/pages/HomePage/HomePage.js, src/pages/HomePage/Splash.js
In this PR: 
- The first section of Home Page height has been update.
- Margin around search box and About section has been set.
Related Ticket: PPDC-695
=> PPDC-695-fix-02: update MinHeight and Margin under Home page

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR:
- 28px of Left and right margin has been added to PCDN page
- Reduce top margin for the main title for mobile
- Reduce the minimum width for the Search Container
Related Ticket: PPDC-685
=> PPDC-685: add left and right margin of 28px to PCDN page

src/pages/HomePage/HomeBox.js, src/pages/HomePage/HomePage.js, src/pages/HomePage/Splash.js
In this PR:
- Small style has been applied under Home page
Related Ticket: PPDC-695
=> PPDC-695-fix-03: Update Home page style

src/components/NCINavBar/NavBar.js, src/components/NCINavBar/SmallerScreenNB.js
In this PR:
- Issue on NCI NavBar has been fix. On Smaller window height, Navbar will have auto vertical scroller.
Related Ticket: CCDIMTP-80
=> CCDIMTP-80: fix NCI navbar overlap

src/components/RMTL/RMTLPopover.js
In this PR:
- Small outdated text has been updated from "Open Targets" to "Molecular Targets"
Related ticket: CCDIMTP-119
=> CCDIMTP-119

src/components/NCINavBar/SmallerScreenNB.js, src/components/NCINavBar/components/DropdownItemsMenu.js, src/components/NCINavBar/index.js
In this PR:
- Add FDA PMTL Documentation page into the Nav bar for better visibility
- Refactor code
Related Ticket: CCDIMTP-48, CCDIMTP-49
=> CCDIMTP-48: Add FDA PMTL Documentation into NavBar

src/sections/common/OpenPedCanSomaticAlterations/utils.js
In this PR:
- Update interpreter to support `exportValue` for configuration file
- Refactor code
Related Ticket: CCDIMTP-134
=> CCDIMTP-134

src/config.js, src/sections/evidence/OpenPedCanGeneExpression/Body.js, src/sections/evidence/OpenPedCanSomaticAlterations/Body.js, src/sections/target/OpenPedCanGeneExpression/Body.js, src/sections/target/OpenPedCanSomaticAlterations/Body.js
Small PR to update codebase with using the main branch from mtp-config repo
=> CCDIMTP-134-Update

package.json
Small PR to update content for package.json
=> CCDIMTP-77

src/sections/common/OpenPedCanSomaticAlterations/utils.js
In this PR:
- Support to interpret `comparator` property.
- Take care edge cases for `interpretConfig()` when value is undefined, null, etc.
Related ticket: CCDIMTP-131
=> CCDIMTP-131

src/pages/APIPage/APIPage.js
=> update the api page wording

src/components/RMTLTable.js, src/pages/PMTLPage/PMTLPage.js
In this PR:
- Column shift caused by sorting functionality is fixed for the Table under `FDA Pediatric Molecular Target Lists` page
Related ticket: CCDIMTP-19
=> CCDIMTP-19

src/components/NCINavBar/components/DropdownItemsMenu.js, src/components/NCINavBar/components/DropdownMenu.js, src/components/NCINavBar/index.js, src/pages/APIPage/APIPage.js, src/pages/APIPage/SomaticAlterationsQuery.gql
add API link to the nav menu  and add Query in the API page
=> add API link to the nav menu  and add Query in the API page

src/pages/APIPage/APIPageWrapper.js
In this PR:
- Each time user visit the API page, the page will focus on the top.
Related Ticket: CCDIMTP-265
=> CCDIMTP-265

src/pages/ChangeLogPage/ChangeLogView.js
In this PR:
- The Change that has been made under mtp-config in this [PR](https://github.com/CBIIT/mtp-config/pull/22) is supported.
- OpenPedCan Analyses version under Change log page is updated base on mtp-config
Related Ticket: CCDIMTP-385
=> CCDIMTP-385: Update Change Log version for OpenPedCan Analyses
