CBIIT/mtp-frontend

src/sections/evidence/SomaticMutation/SnvByGeneTab.js
In this PR, The SNY By Gene table for "PedcBio PedOT oncoprint plot URL" and "PedcBio PedOT mutations plot URL" column are now linking to the right URL by updating the correct fieldName.
=> fix: PedcBioPedotPlotURL 

src/pages/PMTLDocPage/index.js, src/pages/PMTLPage/PMTLPage.js
This PR fix a bug that is causing the Mapping Description column content to not show up in the PMTL Landing Page table. I have also updated the variable names to reflect the change from "Reformat Method" to "Mapping Description"
=> Fix: PMTL Table for Mapping Description Column

src/components/Link.js
change the behavior of external link, which will open in a new tab instead of replacing current tab
=> Open External link in a new tab. 

src/sections/common/OpenPedCanSomaticMutations/SnvByGeneTab.js
In this PR, two missing columns ("Frequency in primary tumors" and
"Total relapse tumors mutated Over Relapse tumors in dataset") are added to SNV by Gene table under OpenPedCan Somatic Mutations (SM) widget for both Target & Evidence Page
=> PPDC-284: Add two missing columns for SNV by Gene table

src/components/Table/DataDownloader.js, src/sections/common/OpenPedCanGeneExpression/Body.js
In this PR:
-	A new prop called “captionLabel” is added to “components/Table/DataDownloader” to allow for users to customize the “Download table as” text found on the top right corner of widgets that allow user to download the data.
-	Updated “OpenPedCan Gene Expression” widget text from “Download table as” to “Download data as”.
Related Ticket: PPDC-350
=> PPDC-350 (captionLabel)

src/components/NCIFooter/Footer.js, src/components/NCIFooter/index.js
In this PR, the footer has been updated. Previously, there was a logo of "Frederick National laboratory for Cancer Research" that take users out to https://frederick.cancer.gov/. Now, it's replaced by a simple text that says "National Cancer Institute at the National Institutes of Health"
Related Ticket: PPDC-385
=> PPDC-385 (Update footer Title)

src/sections/common/OpenPedCanSomaticAlterations/Body.js, src/sections/common/OpenPedCanSomaticAlterations/utils.js, src/sections/evidence/OpenPedCanSomaticAlterations/Body.js, src/sections/target/OpenPedCanSomaticAlterations/Body.js
In this PR:
The default tab for OpenPedCan Somatic Alterations (SA) widget under Target and Evidence Page has been fix to not allow disabled tab as default tab. With the current fix, default tab will always have data.
Related ticket: PPDC-390
=> PPDC-390 (fix: default tab for SA widget )

src/pages/AboutPage/AboutView.js
In this PR:
Fix the items list below.
-Dropdown toggles, make sure the arrow points down when toggle is open
-Dropdown toggle labels: Inter Regular, size 19
-Dropdown toggle label Acronyms: Inter Medium (slightly thicker weight), size 16
-Padding on top of text from edge of toggle box: 20 px, same for bottom
-remove divider above PC Data Visualizations
-lose drop shadow in Change Log boxes
-lose white space before footer
Related ticket: PPDC-395
=> Update the style of about page

src/components/Summary/SummaryItem.js
In this PR, Scrolling from Summary to Detail Widget has been fixed. Before, the title and some part of the body of the detail widget have been covered. Now, the defect has been fixed and scrolling from summary widget ends at the start of every detail widget.
Related Ticket: PPDC-389
=> Fix: Scrolling from Summary to Detail Widget (PPDC-389)

src/pages/DiseasePage/ClassicAssociations.js, src/pages/TargetPage/ClassicAssociations.js
In this PR, the content that direct user to the Pediatric Cancer Data Navigation Page have been updated under both the Target and Disease associated page
Text update is: "Additional pediatric cancer data may be found by using the search tool on the [_**Pediatric Cancer Data Navigation**_] page."
=> PPDC-395(update text that direct user to Pediatric Cancer Data Navigation Page)

src/pages/PedCancerDataNavPage/CHOPPage.js
In this PR, The description of Pediatric Cancer Data Navigation Page has been updated to give a user more clarity on the type of result the page will provide.
Related Ticket: PPDC-436
=> PPDC-436 (update descriptive text on the Pediatric Cancer Data Navigation Page)

src/pages/AboutPage/AboutView.js
In this PR:
- The page description for the `Pediatric Cancer Data Navigation` has been added under `About Page`, specifically in the `Pediatric Cancer Data Visualizations` section. 
- Along updating the about page, small text fix has been done from `OpenPedCan Somatic Mutations `to `OpenPedCan Somatic Alterations`.
=> PPDC-448 (Add Pediatric Cancer Data Navigation Page description and text fix under About Page)

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR:
- Showing and hiding the second section of Pediatric Cancer Data Navigation Page has been fixed.
- Second section will be hidden when user first visit the Nav Page
- Once a user Search and select from drop down menu and click “Search”, the second section will always be shown afterwards.
- The data in the second section will update only once user click the search button with new Gene symbol or Disease input
- Search Button will be disabled if both Gene Symbol and Disease are empty
Related Ticket: PPDC-456
=> PPDC-456 (Fix: Hide/Show Second Section of Nav page)

src/pages/PedCancerDataNavPage/EntitySelect.js, src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR the design for Pediatric Cancer Data Navigation Page has been update with the following:
-  Wrap the text under the title, wrap it to a second line starting at "containing 43,8880..."
- Update Sub Header/title color from black to "#5c5f5e"
- Search bar is too much wide. So it has been closely match with Hannah Design as follow:
- Space between "Gene Symbol:" and line should be 10 px wide, apply the same rule with "Disease:"
- Move search icons to sit on top of line, and eliminate the space it was sitting on, so space between two search criteria should be approx 35 px
- "x" should also sit on top of line
- make sure lines under both criteria are 275 px wide each
- Color of search box is "#3488c8"
-Keep the rest of page as is
=> PPDC-422(Design Update for Pediatric Cancer Data Navigation Page)

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
In this PR, The links under the Pediatric Cancer Data Navigation page has been updated from opening in the same tab to a new tab. Now, Gene Symbol/Target, Disease, and the Evidence links will all open in a new tab.
Related ticket: PPDC-467
=> PPDC-467(Fix: Opening link in new Tab for Gene Symbol and Disease under PCDN page)

src/pages/PedCancerDataNavPage/EntitySelect.js
Navigate to the Pediatric Cancer Data Navigation page.
Click on the Disease drop down and scroll up and down to view the entries.
Seeing the naming convention issues of the entries.
The fix capitalize entries, name of disease follows same  naming convention.
=> Fix naming convention issue on Nav page

src/pages/DiseasePage/ClassicAssociations.js, src/pages/TargetPage/ClassicAssociations.js
In this PR:
- The Association Tab under Disease and Target has been updated to emphasis the link to Pediatric Cancer Data Navigation (PCDN) page.
- Update Descriptive text from "Additional pediatric cancer data may be found by using the search tool on the [Pediatric Cancer Data Navigation] page." to "Additional pediatric cancer data may be found at: [Pediatric Cancer Data Navigation]"
Related Ticket: PPDC-482
=> PPDC-482(emphasize link to PCDN page under Disease/Target Association page)

src/components/NCIFooter/Footer.js
In this PR, Space between a word and colon that are not needed have been removed under Footer.
Related Ticket: PPDC-501
=> PPDC-501(Fix: remove unneeded space from footer)

src/components/NCINavBar/NavBarView.js
In this Pr:
- NCI Nav Menu has been updated. Specifically the Pediatric Cancer Data Navigation(PCDN) button's background color has been update from "#355e00"(darker green) to "#437503"(brighter green)
- On Hover background color to "#437503" is also included.
=> PPDC-480 (Update background color for PCDN Nav Menu)

src/pages/HomePage/HomeBox.js
In this PR:
- HomePage has been updated. Specifically, the link text to Pediatric Cancer Data Navigation page has changed from "Explore **the** Pediatric Cancer Data Navigation" to "Explore **our** Pediatric Cancer Data" ~~Navigation"~~
Related Ticket: PPDC-505
=> PPDC-505 (Update Link text to PCDN under HomePage )

src/pages/PedCancerDataNavPage/PedCancerDataNavPage.js
in this PR:
- White space under footer is now removed and replace by adding space above footer when user zoom out the PCDN page.
- align info and result text to be center
- refactor grid layout and code.
Related Ticket: PPDC-504
=> PPDC-504(Fix: Remove white space under the footer on the PCDN page)

src/pages/PMTLDocPage/index.js
In this PR:
- A text and link that says, "To view and download previous interpretations of the PMTL and the detailed changelog, access the [archive](https://www.genenames.org/download/custom/)." under PMTL Documentation page has been removed.
=> PPDC-527 (fix: remove incomplete archive text and link) | MVP

src/pages/PMTLDocPage/index.js
In this PR:
- Under FDA PMTL Documentation, link behavior for FDA PMTL Landing Page has been updated to open in the same tab.
- Refactor all link under FDA PMTL Documentation to use OT `Link` component.
=> PPDC-528 ( Fix: link behavior under FDA PMTL Documentation | MVP)

src/pages/PMTLPage/PMTLPage.js
In this PR:
- Under FDA PMTL Landing page, user can download the table records using JSON/CSV/TSV file format.
- Before the column name for JSON and CSV/TSV were different. With this PR, all downloaded column will follow the camelCase format.
- The following are the updated Column names:
- ensemblID
- targetSymbol
- designation
- fdaClass
- fdaTarget
- mappingDescription
=> PPDC-524 (Fix: column name for FDA PMTL Downloaded file | MVP)

src/components/ExternalLinkIcon.js, src/pages/AboutPage/AboutView.js, src/pages/HomePage/HomePage.js, src/pages/PMTLDocPage/index.js, src/pages/PMTLPage/PMTLPage.js
In this PR:
- Reusable ExternalLinkIcon component is created
- External link Icon has been added for all external link under FDA PMTL Landing and Documentation Page.
- Update Home and About Page to use ExternalLinkIcon component
- Add scroll to Top functionality and refactor codes
Related Ticket: PPDC-539
=> PPDC-539 (Add External link Icon | MVP)

src/pages/AboutPage/AboutView.js, src/pages/HomePage/HomePage.js
In this PR: 
- Spelling issue is fixed for "_Open Target**s** Platform_" ("**s**" character has been added at the end of Target). Spelling fix occur three times under About page and once under Home page.
- About Page:
- "...is a National Cancer Institute (NCI) instance of the [Open Target Platform](https://platform.opentargets.org/)..."
- "The [Open Target Platform](https://platform.opentargets.org/) is the open-source infrastructure upon which the Molecular ..."
- "Detailed Change Log:[ Open Target Platform](https://platform-docs.opentargets.org/change-log)"
- Home Page:
- "... is an NCI-supported instance of the[ Open Target Platform](https://platform.opentargets.org/)..."
- Spelling issue is fixed for "_Molecular Target**s** Platform_" ("**s**" character has been added at the end of …
=> PPDC-564 (Fix: Add character "s" at the end of "Target" for MTP and OTP)

src/pages/AboutPage/AboutView.js
In this PR:
- Spelling issues under About Page are fixed.
- Remove character 's' from "FDA Pediatric Molecular **Targets** Lists" to be "FDA Pediatric Molecular **Target** Lists"
- Add character 's' to "FDA Pediatric Molecular Target **List**" to be "FDA Pediatric Molecular Target **Lists**"
- Remove space character before closing quotation mark
=> PPDC-567 (Fix misspelling under About page)

src/pages/AboutPage/AboutView.js
In this PR:
- Under About page, the space between the dataset section has been updated to be more consistent. A total of 120px has been added.
- 85px of space has been added at the end of "Pediatric Cancer Data Visualizations" before the Change log section and equally 85px of space has been added before the "Change log" Sub-header.
Related Tickets: PPDC-544 and PPDC-573
=> PPDC-544 (Update space consistency under About page)

src/components/NCILogoBar/index.js
In this PR, the MTP Logo URL has been updated to capture the change from https://github.com/CBIIT/mtp-frontend/pull/166
Related Ticket: PPDC-583
=> update logo source

src/components/Table/DataTable.js, src/components/Table/Table.js, src/components/Table/TableHeader.js, src/components/Table/tableStyles.js, src/sections/common/OpenPedCanSomaticAlterations/CnvByGeneTab.js, src/sections/common/OpenPedCanSomaticAlterations/FusionByGeneTab.js, src/sections/common/OpenPedCanSomaticAlterations/FusionTab.js, src/sections/common/OpenPedCanSomaticAlterations/SnvByGeneTab.js, src/sections/common/OpenPedCanSomaticAlterations/SnvByVariantTab.js, src/sections/common/OpenPedCanSomaticAlterations/utils.js
In this PR:
- Sticky Header functionally has been added back to the Table component. Previously it has been added and removed from [OTP](https://github.com/opentargets/platform-app) here: 
- https://github.com/opentargets/platform-app/pull/187
- https://github.com/opentargets/platform-app/commit/243d8fe1bbc0f8326c193507abeebe678e1a6ba4
- All tables under OpenPedCan Somatic Alterations (SA) widget has been updated to include:
-  Sticky Header functionality
- Wrap row content 
- Set a minimum column width of 160px 
- Add Label Style to customize Table Header padding to reduce Table header height
Related Ticket: PPDC-384, PPDC-643
=> PPDC-643 (Add Sticky Header and update style for SA tables )

src/sections/common/KnownDrugs/Body.js
In this PR:
- Sticky Header functionality has been removed from `KnownDrugs` widgets.
- At the moment, only `OpenPedCan Somatic Alterations` widgets has the Sticky header functionality.
=> remove stickyheader for KnownDrugs widgets

src/constants.js, src/pages/ChangeLogPage/ChangeLogView.js, src/pages/HomePage/Version.js
In this PR:
- Reduce margin and padding under Change log page to provide space for smaller screen size
- Update page title from `About Page` to `Change Log`
- Update Link URL that point from `Home>Search Box>version` to `Change Log `page
- Remove unused style
Related Ticket: PPDC-705
=> PPDC-705 (Mobile responsiveness for Change Log page)

src/components/NCILogoBar/LogoBar.js, src/pages/HomePage/HomeBox.js, src/pages/HomePage/HomePage.js, src/pages/HomePage/Splash.js
in this PR:
- LogoBar and Hamburger/close menu Icon has been closely aligned. 
- Search Box under Home page has a marginTop of 100px, to avoid overlap issue by Header
- Home Page now has Minimum Height of 700px in order to properly display the search box and splash for smaller screen size.
Related Ticket: PPDC-695
=> PPDC-695-fix: (Fix: Align LogoBar and Hamburger menu Icon)

src/config.js
Update the efo yaml to lock down to the version 22.04. Current efo yaml based on the verion 22.06 which  break some functions on our site. Downgrade to 22.04 can solve some issues founded.
=> Update the efo yaml to lock down to the version 22.04

src/components/NCINavBar/SmallerScreenNB.js, src/pages/AboutPage/AboutView.js, src/pages/PMTLDocPage/index.js
In this PR:
- "infographic" under About page is centered
- contact email "ncichildhoodcancerdatainitiative@mail.nih.gov" and "." are wrapped. Since the email has a lot of character, the font size has been decreased to 11px for ViewPort of < 450px
- Fix NavBar warning
- Update  the two table under FDA PMTL Doc page with a minimum width and auto scroll to allow mobile responsiveness
Related Ticket: PPDC-704
=> PPDC-704-fix: refactor style for smaller screen size 

src/pages/AboutPage/AboutView.js, src/pages/PMTLDocPage/index.js
In this PR:
- Email Font size has been increase under About page 
- FDA PMTL Doc Table has overFlowX set to scroll to be more visible for users
Related Ticket: PPDC-704
=> PPDC-704-fix-02

src/pages/ChangeLogPage/ChangeLogView.js
In this PR:
- Under Change log page, The URL to OTP detailed change log has been updated.
Related Ticket: PPDC-760
=> PPDC-760: update URL for OTP detailed change log

src/App.js, src/components/NCINavBar/index.js, src/components/RMTL/RMTLPopover.js, src/constants.js, src/pages/AboutPage/AboutView.js, src/pages/ChangeLogPage/ChangeLogView.js, src/pages/PMTLDocPage/index.js, src/pages/PMTLPage/PMTLPage.js
In this PR, two page has been renamed:
- Rename `FDA PMTL Landing Page` to `FDA Pediatric Molecular Target Lists`
- Rename `FDA PMTL Documentation` to `MTP PMTL Documentation`
- Rename internal URL from `/fda-pmtl-docs` to `/mtp-pmtl-docs`
Related Ticket: CCDIMTP-49, CCDIMTP-47
=> CCDIMTP-49

src/App.js, src/pages/AboutPage/AboutView.js
In this PR:
- Route to Data Downloads page is removed from MTP
- Route Variants page is removed from MTP
- About Page is updated to link out to OTP Data Downloads page.
Related Ticket: CCDIMTP-179
=> CCDIMTP-179

src/components/NCIFooter/Footer.js
Small PR to fix width issue for version container under Footer.
- Now, the container minimum width is set to `fit-content` to accommodate any length of version.
=> Fix: version container under Footer

src/constants.js, src/pages/AboutPage/AboutView.js, src/pages/ChangeLogPage/ChangeLogView.js, src/sections/evidence/OpenPedCanGeneExpression/Description.js, src/sections/evidence/OpenPedCanSomaticAlterations/Description.js, src/sections/target/OpenPedCanGeneExpression/Description.js, src/sections/target/OpenPedCanSomaticAlterations/Description.js
In this PR, All existing MTP links to CHoP's OpenPedCan-analysis repo are replaced with links to CHoP's documentation repo.
Following two url are replaced by (https://github.com/PediatricOpenTargets/documentation)
- https://github.com/PediatricOpenTargets/OpenPedCan-analysis
- https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/4fb04fe60754b90da3c241dbb8b727c3722487cc/doc/release-notes.md
=> CCDIMTP-366

src/pages/AboutPage/AboutView.js
In this PR:
-  CHOP P30 Panel is added Under Pediatric Cancer Data Sources section in the About page
=> CCDIMTP-410: CHOP P30 Panel

src/components/NCINavBar/index.js
In this PR, a missing `/` is added to correctly navigate to the Latest Release pdf from any page in the application.
Bug Ticket: CCDIMTP-413
=> CCDIMTP-413
